# Generated by Django 4.2.1 on 2023-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bspl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bav', models.CharField(max_length=10000)),
                ('bu', models.CharField(max_length=10000)),
                ('bv', models.CharField(max_length=50000)),
                ('bq', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='btopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_id', models.CharField(max_length=500)),
                ('btname', models.CharField(max_length=500)),
                ('bsurano', models.IntegerField()),
                ('bsuraname', models.CharField(max_length=100)),
                ('bverseno', models.CharField(max_length=200)),
                ('bverse', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('desc', models.TextField(max_length=5000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='spl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('av', models.CharField(max_length=1000)),
                ('eu', models.CharField(max_length=1000)),
                ('v', models.CharField(max_length=50000)),
                ('q', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=500)),
                ('tname', models.CharField(max_length=500)),
                ('surano', models.IntegerField()),
                ('suraname', models.CharField(max_length=100)),
                ('verseno', models.IntegerField()),
                ('verse', models.CharField(max_length=50000)),
            ],
        ),
    ]
